export enum SchoolPermission {
  // Dashboard
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',

  // Organization Management
  VIEW_ORGANIZATIONS = 'VIEW_ORGANIZATIONS',
  CREATE_ORGANIZATION = 'CREATE_ORGANIZATION',
  EDIT_ORGANIZATION = 'EDIT_ORGANIZATION',
  DELETE_ORGANIZATION = 'DELETE_ORGANIZATION',
  APPROVE_ORGANIZATION = 'APPROVE_ORGANIZATION',

  // Branch Management
  VIEW_BRANCHES = 'VIEW_BRANCHES',
  CREATE_BRANCH = 'CREATE_BRANCH',
  EDIT_BRANCH = 'EDIT_BRANCH',
  DELETE_BRANCH = 'DELETE_BRANCH',

  // User Management
  VIEW_USERS = 'VIEW_USERS',
  CREATE_USER = 'CREATE_USER',
  EDIT_USER = 'EDIT_USER',
  DELETE_USER = 'DELETE_USER',
  APPROVE_USER = 'APPROVE_USER',
  MANAGE_USER_PERMISSIONS = 'MANAGE_USER_PERMISSIONS',

  // Staff Management
  VIEW_STAFF = 'VIEW_STAFF',
  CREATE_STAFF = 'CREATE_STAFF',
  EDIT_STAFF = 'EDIT_STAFF',
  DELETE_STAFF = 'DELETE_STAFF',

  // Class Management
  VIEW_CLASSES = 'VIEW_CLASSES',
  CREATE_CLASS = 'CREATE_CLASS',
  EDIT_CLASS = 'EDIT_CLASS',
  DELETE_CLASS = 'DELETE_CLASS',

  // Subject Management
  VIEW_SUBJECTS = 'VIEW_SUBJECTS',
  CREATE_SUBJECT = 'CREATE_SUBJECT',
  EDIT_SUBJECT = 'EDIT_SUBJECT',
  DELETE_SUBJECT = 'DELETE_SUBJECT',

  // Student Management
  VIEW_STUDENTS = 'VIEW_STUDENTS',
  CREATE_STUDENT = 'CREATE_STUDENT',
  EDIT_STUDENT = 'EDIT_STUDENT',
  DELETE_STUDENT = 'DELETE_STUDENT',

  // Timetable
  VIEW_TIMETABLE = 'VIEW_TIMETABLE',
  CREATE_TIMETABLE = 'CREATE_TIMETABLE',
  EDIT_TIMETABLE = 'EDIT_TIMETABLE',
  DELETE_TIMETABLE = 'DELETE_TIMETABLE',

  // Grading
  VIEW_GRADES = 'VIEW_GRADES',
  CREATE_GRADE = 'CREATE_GRADE',
  EDIT_GRADE = 'EDIT_GRADE',
  DELETE_GRADE = 'DELETE_GRADE',

  // Performance
  VIEW_PERFORMANCE = 'VIEW_PERFORMANCE',
  GENERATE_REPORTS = 'GENERATE_REPORTS',

  // Payments
  VIEW_PAYMENTS = 'VIEW_PAYMENTS',
  CREATE_PAYMENT = 'CREATE_PAYMENT',
  EDIT_PAYMENT = 'EDIT_PAYMENT',
  DELETE_PAYMENT = 'DELETE_PAYMENT',
  VIEW_FEE_STRUCTURE = 'VIEW_FEE_STRUCTURE',
  MANAGE_FEE_STRUCTURE = 'MANAGE_FEE_STRUCTURE',

  // M-Pesa
  INITIATE_MPESA_PAYMENT = 'INITIATE_MPESA_PAYMENT',
  VIEW_MPESA_TRANSACTIONS = 'VIEW_MPESA_TRANSACTIONS',
  DELETE_MPESA_TRANSACTION = 'DELETE_MPESA_TRANSACTION',

  // Approvals
  VIEW_APPROVALS = 'VIEW_APPROVALS',
  MANAGE_APPROVALS = 'MANAGE_APPROVALS',

  // Reports
  VIEW_REPORTS = 'VIEW_REPORTS',
  EXPORT_REPORTS = 'EXPORT_REPORTS',

  // System Admin
  SYSTEM_SETTINGS = 'SYSTEM_SETTINGS',
}
